# Default values for bytebase.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

bytebase:
  option:
    port: 8080
    existingPgURLSecret: ""
    existingPgURLSecretKey: ""
    pg:
    data: /var/opt/bytebase
    external-url: "https://www.bytebase.com/docs/get-started/install/external-url"
    disable-sample: false
  version: 2.4.1
  registryMirrorHost: ""
  persistence:
    storage: 2Gi
    enabled: false
    storageClass: ""
    existingClaim: ""
