# Default values for bytebase.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

bytebase:
  option:
    port: 8080
    # You should set this to the URL where users visits Bytebase.
    external-url: https://www.bytebase.com/docs/get-started/install/external-url
    pg: postgresql://user:secret@host:port/dbname
    data: /var/opt/bytebase
  version: 1.7.0
  storage: 2Gi
