version: "3.7"

services:
  bb:
    # platform: linux/amd64
    image: bytebase/bytebase:${BB_VERSION}
    init: true
    container_name: bytebase
    restart: always
    ports:
      - 8080:8080
    # # Uncomment the following lines to persist data
    # volumes:
    #   - ~/.bytebase/data:/var/opt/bytebase
    command: ["--data", "/var/opt/bytebase", "--port", "8080"]

  mysql-db:
    image: mysql
    platform: linux/amd64
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
    volumes:
      - ./test_schema/mysql:/docker-entrypoint-initdb.d
