# Using `git update-index --assume-unchanged scripts/.air.toml` to let git untrack it.
root = "."
tmp_dir = ".air"

[build]
bin = './.air/bytebase --port 8080 --data . --debug --disable-sample'
## Use --tags "store.db" to enable SQL query logging against our metadata db.
## Use -gcflags="all=-N -l" to disable inlining and optimization

cmd = """
  go build \
  -gcflags="all=-N -l" \
  --tags "minimal" \
  -o ./.air/bytebase ./backend/bin/server/main.go"""
delay = 500
exclude_dir = [
  ".air",
  "backend/server/dist",
  "bytebase-build",
  "backend/server/dist",
  "docs",
  "frontend",
  "helm-charts",
  "proto",
  "quickstart",
  "scripts",
  "vendor",
]
exclude_file = []
exclude_regex = []
exclude_unchanged = false
follow_symlink = false
send_interrupt = true
kill_delay = 1000
