root = "."
tmp_dir = ".air"

[build]
  bin = "./.air/bytebase --port 8080 --frontend-port 3000 --data ."
  cmd = "go build -gcflags=all=\"-N -l\" -o ./.air/bytebase ./bin/server/main.go"
  delay = 1000
  exclude_dir = [".air", "vendor", "frontend", "docs"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  send_interrupt = true
  kill_delay = 1000
  full_bin = ""
