name: build release image and push to docker hub

on:
  push:
    branches:
      # Run on pushing branches like `release/1.0.0`
      - "release/v*.*.*"

jobs:
  build-release-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract build args
        # Extract version from branch name
        # Example: branch name `release/v1.0.0` sets up env.BB_VERSION=1.0.0
        run: |
          echo "BB_VERSION=${GITHUB_REF_NAME#release/v}" >> $GITHUB_ENV
          echo "GIT_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV
          echo "BUILD_USER=$(id -u -n)" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: bytebase_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: bytebase/bytebase:${{ env.BB_VERSION }}
          build-args: |
            VERSION=${{ env.BB_VERSION }}
            GIT_COMMIT=${{ env.GIT_COMMIT }}
            BUILD_TIME=${{ env.BUILD_TIME }}
            BUILD_USER=${{ env.BUILD_USER }}
      - name: Image digest
        run: echo "Successfully pushed bytebase/bytebase:${{ env.BB_VERSION }} ${{ steps.bytebase_build.outputs.digest }}"
      - name: Build and push bb CLI
        id: bb_build
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.bb
          push: true
          tags: bytebase/bb:${{ env.BB_VERSION }}
          build-args: |
            VERSION=${{ env.BB_VERSION }}
            GIT_COMMIT=${{ env.GIT_COMMIT }}
            BUILD_TIME=${{ env.BUILD_TIME }}
            BUILD_USER=${{ env.BUILD_USER }}
      - name: Image digest
        run: echo "Successfully pushed bytebase/bb:${{ env.BB_VERSION }} ${{ steps.bb_build.outputs.digest }}"

  release-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.10.0
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "pnpm"
          cache-dependency-path: "frontend/pnpm-lock.yaml"
      - run: pnpm install --frozen-lockfile
        working-directory: frontend
      - run: pnpm release
        working-directory: frontend
      - name: Extract version
        run: git tag ${GITHUB_REF_NAME#release/v}
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: "Release"
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release
