name: Build push action image

on:
  workflow_dispatch:
  push:
    branches:
      - 'release/*.*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Extract build args
        id: extract_build_args
        run: |
          if [[ "${{ github.ref_name }}" =~ ^release/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            VERSION=$(echo "${{ github.ref_name }}" | sed 's/release\///')
          else
            VERSION="latest"
          fi
          echo "IMAGE_TAG=${VERSION}" >> $GITHUB_ENV
          echo "GIT_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: scripts/Dockerfile.action
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            bytebase/bytebase-action:${{ env.IMAGE_TAG }}
          build-args: |
            VERSION=${{ env.IMAGE_TAG }}
            GIT_COMMIT=${{ env.GIT_COMMIT }}
  build-debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Extract build args
        id: extract_build_args
        run: |
          if [[ "${{ github.ref_name }}" =~ ^release/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            VERSION=$(echo "${{ github.ref_name }}" | sed 's/release\///')
          else
            VERSION="latest"
          fi
          echo "IMAGE_TAG=${VERSION}" >> $GITHUB_ENV
          echo "GIT_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: scripts/Dockerfile.action-debian
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            bytebase/bytebase-action:${{ env.IMAGE_TAG }}-debian
          build-args: |
            VERSION=${{ env.IMAGE_TAG }}
            GIT_COMMIT=${{ env.GIT_COMMIT }}