name: Build release artifacts and draft release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build-linux-binary:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.5
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.8.0
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: pnpm
          cache-dependency-path: "frontend/pnpm-lock.yaml"
      - run: pnpm install --frozen-lockfile
        working-directory: frontend
      - run: pnpm release
        working-directory: frontend
      - name: Build
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --skip-publish --config scripts/.goreleaser-for-linux.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: bytebase-linux
          path: dist/bytebase*
  draft-release:
    needs: [build-linux-binary]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.5
      - name: Make directories
        run: |
          mkdir -p ./bytebase-build/linux
      - name: Download linux binaries
        uses: actions/download-artifact@v3
        with:
          name: bytebase-linux
          path: ./bytebase-build/linux
      - name: Merge checksum file
        run: |
          cd ./bytebase-build
          cat ./linux/bytebase*checksums.txt >> checksums.txt
          rm ./linux/bytebase*checksums.txt
      - name: Release
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --config scripts/.goreleaser-release.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
