name: Docker tag latest

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Tag latest image in DockerHub
        run: |
          RELEASE_VERSION=${GITHUB_REF_NAME#release/}
          echo version: ${RELEASE_VERSION}
          docker buildx imagetools create -t bytebase/bytebase:latest bytebase/bytebase:${RELEASE_VERSION}
          docker buildx imagetools create -t bytebase/bytebase-action:latest bytebase/bytebase-action:${RELEASE_VERSION}
          docker buildx imagetools create -t bytebase/bytebase-action:latest-debian bytebase/bytebase-action:${RELEASE_VERSION}-debian
      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-shanghai.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
      - name: Tag latest image in Aliyun Container Registry
        run: |
          RELEASE_VERSION=${GITHUB_REF_NAME#release/}
          echo version: ${RELEASE_VERSION}
          docker buildx imagetools create -t registry.cn-shanghai.aliyuncs.com/bytebase/bytebase:latest bytebase/bytebase:${RELEASE_VERSION}
          docker buildx imagetools create -t registry.cn-shanghai.aliyuncs.com/bytebase/bytebase:${RELEASE_VERSION} bytebase/bytebase:${RELEASE_VERSION}
          docker buildx imagetools create -t registry.cn-shanghai.aliyuncs.com/bytebase/bytebase-action:${RELEASE_VERSION} bytebase/bytebase-action:${RELEASE_VERSION}
          docker buildx imagetools create -t registry.cn-shanghai.aliyuncs.com/bytebase/bytebase-action:${RELEASE_VERSION}-debian bytebase/bytebase-action:${RELEASE_VERSION}-debian
          docker buildx imagetools create -t registry.cn-shanghai.aliyuncs.com/bytebase/bytebase-action:latest bytebase/bytebase-action:${RELEASE_VERSION}
          docker buildx imagetools create -t registry.cn-shanghai.aliyuncs.com/bytebase/bytebase-action:latest-debian bytebase/bytebase-action:${RELEASE_VERSION}-debian
