on:
  pull_request:
    paths:
      - 'backend/migrator/migration/**.sql'

jobs:
  sql-review:
    runs-on: ubuntu-latest
    name: SQL Review
    steps:
      - uses: actions/checkout@v4
      - name: Check SQL
        uses: bytebase/sql-review-action@1.0.0
        with:
          override-file-path: ./sql-review-override.yml
          database-type: POSTGRES
