name: "Staging Env"

on:
  release:
    types: [ prereleased ]
  workflow_dispatch:

jobs:
  initiate-render-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "trigger render's webhook"
        run: curl ${{ secrets.RENDER_STAGING_DEPLOY_HOOK }}
